version: '3.4'

services:
  web:
    image: justaprogrammeraspnetcoreauthsslproxy
    build:
      context: .
      dockerfile: JustAProgrammer.AspNetCore.Auth.SslProxy/Dockerfile
  ssl:
    image: fsouza/docker-ssl-proxy
    environment:
      TARGET_PORT: "80"
      TARGET_HOST: "web"