version: '3.4'

services:
  web:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      #AzureAd__ForceSslRedirectUri: "true"
      #AzureAd__ForceSslRedirectPort: "44320"
  ssl:
    environment:
      DOMAIN: sslproxy.aspnetcore.localtest.me
      SSL_PORT: 44330
    ports:
      - "${SSL_PORT}:${SSL_PORT}"